services:
  clothing:
    image: ghcr.io/watsona4/clothing:latest
    build: .
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - clothing
    env_file:
      - .env
    environment:
      - WTW_URL_PREFIX=/wtw
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    ports:
      - "127.0.0.1:8256:8256"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8256/wtw/api/v2/closet', timeout=5).status<400 else sys.exit(1)\""]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis:/data
    env_file:
      - .env
    networks:
      - clothing
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s

networks:
  clothing:
    driver: bridge

volumes:
  redis:
    driver: local
