services:
  clothing:
    image: ghcr.io/watsona4/clothing:latest
    build: .
    restart: unless-stopped
    networks:
      - clothing
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./html:/var/www/html:ro
    ports:
      - 8256:8080
    networks:
      - clothing

networks:
  clothing:
    driver: bridge
